# Generated by Django 4.1.4 on 2022-12-29 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0004_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organizations_managed', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
