# Generated by Django 4.1.4 on 2023-01-02 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_release_sprints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='sprints',
        ),
        migrations.AlterField(
            model_name='release',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.team'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.release'),
        ),
    ]
