# Generated by Django 4.1.4 on 2023-01-02 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_remove_organization_invitation_code_invitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='token',
            new_name='invitation_code',
        ),
    ]
